{
 "title": "Otus app",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket[5m])) by (le))",
     "legendFormat": "1-quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket[5m])) by (le))",
     "legendFormat": "0.99-quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket[5m])) by (le))",
     "legendFormat": "0.95-quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket[5m])) by (le))",
     "legendFormat": "0.5-quantile"
    }
   ]
  },
  {
   "title": "Latency (nginx)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(nginx_ingress_controller_response_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "1-quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_response_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "0.99-quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_response_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "0.95-quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_response_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "0.5-quantile"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(django_http_requests_total_by_method_total[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS (nginx)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(django_http_responses_total_by_status_view_method_total{status=~\"5..\"}[5m])) by(method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate (nginx)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"5..\"}[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}