controller:
  kind: DaemonSet
  
  reportNodeInternalIp: true

  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443

  service:
    type: NodePort

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: otus-promet # этот лейбл здесь нужен чтобы этот service monitor появился в prometheus service doiscovery